global:
  resolve_timeout: 5m

route:
  receiver: "slack"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
- name: "slack"
  # 這裡可以放 slack webhook, email, pagerduty 等
  email_configs:
  - to: "you@example.com"
    from: "alert@example.com"
    smarthost: "smtp.example.com:587"
    auth_username: "user"
    auth_identity: "user"
    auth_password: "password"