version: "3.8"
services:
  # data
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
  
  redis:
    container_name: redis
    image: redis:8.0.5-alpine
    ports:
      - "6379:6379"
  redisinsight:
    container_name: redisinsight
    image: redis/redisinsight:2.70
    ports:
      - "5540:5540"
    environment:
      - RI_REDIS_PORT=6379

  kafka:
    container_name: kafka
    image: apache/kafka:4.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093    
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

      
  postgres:
    container_name: postgres
    image: postgres:15.15-alpine3.22
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d
  # infra
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.7.3
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  tempo:
    image: grafana/tempo:main-7b00d6c
    ports:
      - "3200:3200"   # Tempo HTTP API
      - "4318:4318"   # OTLP/HTTP 接收追蹤
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/data:/tmp/tempo/traces
    command: -config.file=/etc/tempo.yaml
  grafana:
    image: grafana/grafana:12.1
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - tempo